fastlane_require "dotenv"

before_all do
  UI.important "Loading secret environment variables"
  Dotenv.load ".env.secret"
end

default_platform(:ios)

desc "Create on Developer portal and App Store Connect"
lane :create_app do
  produce
end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Sync signing"
  lane :signing do
    match

    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build the binary"
  lane :build do
    signing
    gym
  end

  desc "Deploy to app store"
  lane :release do
    build
    deliver
  end
end
